version: '3.8'
services:
    cadvisor:
      image: google/cadvisor:latest
      container_name: cadvisor
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
      ports:
        - "8080:8080"
      networks:
        - prometheus
networks:
  prometheus:
    external:
      name: prometheus