version: '3.8'
services:
    grafana:
      image: grafana/grafana:10.2.2
      container_name: grafana
      ports:
        - "3000:3000"
      networks:
        - prometheus

networks:
  prometheus:
    external:
      name: prometheus